#!/usr/bin/env python
#
# ethertap_test
#
# tap a given network interface and simulate a virtual host there
#
# the host responds to ARP requests for its mac address and tells its IP.
# the host replies ping requests and als replies UDP packets sent to
# the special port 6800.
#
# use the latter with ./pio_test to measure the performance of UDP transfers.
#

from __future__ import print_function
import argparse

from ethertap import EtherTap
import netpkt.simhost

def ethertap_test(eth_if, ip_addr_str, udp_port, mac_addr_str, verbose=False):
  # parse parameter
  ip_addr = map(int, ip_addr_str.split('.'))
  mac_addr = map(lambda x: int(x,16), mac_addr_str.split(':'))

  print("tapping interface '%s': virtual host mac='%s', ip=%s, udp=%d" % \
    (eth_if, mac_addr_str, ip_addr_str, udp_port))

  # create host simulator
  simhost = netpkt.simhost.SimHost(mac_addr, ip_addr, udp_port, verbose)

  # build tap
  with EtherTap(eth_if, verbose=verbose) as et:
    # send a gracious ARP of my mac to announce my IP
    et.write(simhost.get_init_packet())
    # main loop
    try:
      while True:
        raw_pkt = et.read()
        raw_reply_pkt = simhost.handle_packet(raw_pkt)
        if raw_reply_pkt is not None:
          et.write(raw_reply_pkt)
    except KeyboardInterrupt:
      print("***Break")

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('-v', '--verbose', action='store_true', default=False, help="be verbose")
  parser.add_argument('-i', '--interface', default='en3', help="ethernet interface to tap")
  parser.add_argument('-a', '--address', default='192.168.2.221', help="ip address of virtual host")
  parser.add_argument('-p', '--port', default=6800, type=int, help="udp port of virtual host")
  parser.add_argument('-m', '--mac', default="1a:11:af:a0:47:1a", help="mac address of virtual host")
  args = parser.parse_args()
  ethertap_test(args.interface, args.address, args.port, args.mac, verbose=args.verbose)

if __name__ == '__main__':
  main()
